### PR TITLE
Exists support

### PR DESCRIPTION
**Pull request by cdevienne**

### CODE REVIEW

**Comment by aacanakin** [comment]
Your selectable interface is on every single pull request. I can't detect which commit you're making in this PR

**Comment by cdevienne** [comment]
That would be the two last commits (SQLText & conditional)

**Comment by cdevienne** [comment]
I just rebased the branch to make it clearer

**Comment by aacanakin** [comment]
Can you do that for other PRs?

**Comment by cdevienne** [comment]
Yes, once the one they depend on is merge, starting with this one.

**Pull request closed without merging**
